name: Build
on:
  push:
jobs:
  build-project:
    name: Build Project
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout Project
        uses: actions/checkout@v4
        with:
          submodules: "recursive"

      - name: Perform Commit Linting
        uses: wagoid/commitlint-github-action@v6

      - name: Check Clang Formatting
        uses: RafikFarhad/clang-format-github-action@v6
        with:
          sources: "src/**/*.h,src/**/*.cpp"
          style: file

      - name: Build Project
        uses: threeal/cmake-action@v2